In [1]:
!pip install tensorflow==2.12.0

In [2]:
import tensorflow as tf
from tensorflow.keras import models,layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [3]:
# Set constants
IMAGE_SIZE=(224, 224)
BATCH_SIZE = 32
CHANNELS=3


In [4]:
dataset_path= "/content/drive/MyDrive/Date_dataset"

In [5]:
train_datagen = ImageDataGenerator(
    rotation_range=40,
    rescale=1./255,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.10 # 10% for validation
)

In [6]:
import os
train_generator = train_datagen.flow_from_directory(
    os.path.join(dataset_path, 'train'),  # Path to the training set
    target_size=(IMAGE_SIZE),  # Resize images to 150x150 pixels
    batch_size=BATCH_SIZE,  # Number of images to return in each batch
    class_mode='sparse',
    subset='training',
    shuffle=True
)



Found 1044 images belonging to 9 classes.


In [7]:
for class_name, label in train_generator.class_indices.items():
    print(f"Class: {class_name}, Label: {label}")

Class: Ajwa, Label: 0
Class: Galaxy, Label: 1
Class: Mejdool, Label: 2
Class: Meneifi, Label: 3
Class: NabtatAli, Label: 4
Class: Rutab, Label: 5
Class: Shaishe, Label: 6
Class: Sokari, Label: 7
Class: Sugaey, Label: 8


In [8]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])

    break

[[[0.85098046 0.85098046 0.85098046]
  [0.85098046 0.85098046 0.85098046]
  [0.85098046 0.85098046 0.85098046]
  ...
  [0.85098046 0.8431373  0.8470589 ]
  [0.85098046 0.8431373  0.8470589 ]
  [0.85098046 0.8431373  0.8470589 ]]

 [[0.85098046 0.85098046 0.85098046]
  [0.85098046 0.85098046 0.85098046]
  [0.85098046 0.85098046 0.85098046]
  ...
  [0.85098046 0.8431373  0.8470589 ]
  [0.85098046 0.8431373  0.8470589 ]
  [0.85098046 0.8431373  0.8470589 ]]

 [[0.85098046 0.85098046 0.85098046]
  [0.85098046 0.85098046 0.85098046]
  [0.85098046 0.85098046 0.85098046]
  ...
  [0.85098046 0.8431373  0.8470589 ]
  [0.85098046 0.8431373  0.8470589 ]
  [0.85098046 0.8431373  0.8470589 ]]

 ...

 [[0.82745105 0.82745105 0.82745105]
  [0.82745105 0.82745105 0.82745105]
  [0.82745105 0.82745105 0.82745105]
  ...
  [0.85098046 0.85098046 0.8588236 ]
  [0.85098046 0.85098046 0.8588236 ]
  [0.85098046 0.85098046 0.8588236 ]]

 [[0.82745105 0.82745105 0.82745105]
  [0.82745105 0.82745105 0.82745105]


In [9]:
from PIL import Image
import os

# Path to one of your images in the dataset
image_path = os.path.join(dataset_path, 'train', 'class_name', 'some_image.jpg')

# Open the image
img = Image.open("/content/drive/MyDrive/Date_dataset/test/Galaxy/Galaxy002.jpg")

# Get the size of the image (width, height)
print("Image size (width, height):", img.size)  # Output example: (256, 256)


Image size (width, height): (600, 400)


In [10]:
from os import path
#rescaling
test_datagen=ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
    )

test_generator = test_datagen.flow_from_directory(
    os.path.join(dataset_path, 'test'),  # Path to the validation set
    target_size=(IMAGE_SIZE),  # Resize images to 150x150 pixels
    batch_size=BATCH_SIZE,  # Number of images to return in each batch
    class_mode='sparse'
)

Found 502 images belonging to 9 classes.


In [11]:
# Validation data generator (using the validation split from training data)
validation_generator = train_datagen.flow_from_directory(
    os.path.join(dataset_path, 'train'),
    target_size=(IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="sparse",
    subset='validation', # This uses the validation subset
    shuffle=False
)

Found 112 images belonging to 9 classes.


In [12]:
input_shape= (224, 224,CHANNELS)
n_classes=9
model=models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32,(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64,activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])
# input_shape=(224, 224, 3)
# n_classes=9
# model=models.Sequential([
#     layers.InputLayer(input_shape=input_shape),
#     layers.Conv2D(32,(3,3), activation='relu'),
#     layers.MaxPooling2D((2,2)),
#     layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
#     layers.MaxPooling2D((2,2)),
#     layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
#     layers.MaxPooling2D((2,2)),
#     # Removed some Conv2D and MaxPooling2D layers to prevent the feature maps from becoming too small
#     #layers.Conv2D(64,(3,3), activation='relu'),
#     #layers.MaxPooling2D((2,2)),
#     #layers.Conv2D(64,(3,3), activation='relu'),
#     #layers.MaxPooling2D((2,2)),
#     #layers.Conv2D(64,(3,3), activation='relu'),
#     #layers.MaxPooling2D((2,2)),
#     layers.Flatten(),
#     layers.Dense(64,activation='relu'),
#     layers.Dense(n_classes, activation='softmax'),
# ])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 111, 111, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 109, 109, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 54, 54, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 52, 52, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 26, 26, 64)       0

In [14]:



model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [15]:
trainstep=1044/32
validationstep=112/32
trainstep,validationstep

(32.625, 3.5)

In [16]:
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6)
early_stop = EarlyStopping(monitor='val_accuracy', patience=10, restore_best_weights=True, mode='max')

In [17]:
#fit the model
history=model.fit(
    train_generator,
    # steps_per_epoch=32,
    validation_data=validation_generator,
    # validation_steps=3,
    verbose=1,
    batch_size=32,
    epochs=50,
    callbacks=[reduce_lr, early_stop]
)

Epoch 1/50
33/33 [==============================] - 140s 4s/step - loss: 2.1888 - accuracy: 0.1494 - val_loss: 2.1745 - val_accuracy: 0.1607 - lr: 0.0010
Epoch 2/50
33/33 [==============================] - 141s 4s/step - loss: 2.1839 - accuracy: 0.1590 - val_loss: 2.1753 - val_accuracy: 0.1607 - lr: 0.0010
Epoch 3/50
33/33 [==============================] - 134s 4s/step - loss: 2.1617 - accuracy: 0.1590 - val_loss: 2.0764 - val_accuracy: 0.2054 - lr: 0.0010
Epoch 4/50
33/33 [==============================] - 134s 4s/step - loss: 1.9382 - accuracy: 0.2644 - val_loss: 1.7968 - val_accuracy: 0.2589 - lr: 0.0010
Epoch 5/50
33/33 [==============================] - 134s 4s/step - loss: 1.7042 - accuracy: 0.3123 - val_loss: 1.5587 - val_accuracy: 0.2946 - lr: 0.0010
Epoch 6/50
33/33 [==============================] - 134s 4s/step - loss: 1.5943 - accuracy: 0.3391 - val_loss: 1.5430 - val_accuracy: 0.3750 - lr: 0.0010
Epoch 7/50
33/33 [==============================] - 134s 4s/step - loss: 1.5

In [18]:
scores=model.evaluate(test_generator)

16/16 [==============================] - 110s 7s/step - loss: 0.6952 - accuracy: 0.7291


In [19]:
model.save("/content/drive/MyDrive/saudidattt.h5")